package tingeso.backend;// Generated by Selenium IDE
import lombok.ToString;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Action;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.net.MalformedURLException;

import java.net.URL;
import java.util.*;
import java.util.concurrent.TimeUnit;
import lombok.Data;
import lombok.extern.java.Log;

@Log
@Data
@ToString

public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before

    public void setUp() throws MalformedURLException {
    DesiredCapabilities capabilities = DesiredCapabilities.chrome();
    capabilities.setPlatform(Platform.LINUX);
    capabilities.setVersion("");
    driver = new RemoteWebDriver(new URL("http://157.230.231.153:4444/wd/hub"), capabilities);

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() throws InterruptedException {
    driver.get("http://157.230.231.153/");
    driver.manage().window().setSize(new Dimension(687, 687));
    String expectedTitle="frontend-tingeso";
    String title = driver.getTitle();
    Assert.assertEquals(expectedTitle,title);


  }
}
